function  [nwb, CS] = addSubAna2NWB(nwb, T, CS) 

%% Add anatomical data from histological processing  
CS.CompDataIdx = find(strcmp(T.IDS, CS.cellID));
if ~isempty(CS.CompDataIdx)
   nwb.general_subject = types.core.Subject( ...
    'subject_id', [T.SubjectID{CS.CompDataIdx}, 'W'], ...
         'age', ['P',num2str(round(T.Age_years(CS.CompDataIdx),2)), 'Y'], ...
    'sex', T.Sex(CS.CompDataIdx), 'species', T.Breed(CS.CompDataIdx), ...
    'weight', num2str(T.Weight_Kg(CS.CompDataIdx)),     ... 
     'description', 'basic subject data');      
   CS.corticalArea = T.TissueOrigin(CS.CompDataIdx);
   if ~isempty(T.InitialAccessResistance(CS.CompDataIdx))
    CS.initAccessResistance = num2str(T.InitialAccessResistance(CS.CompDataIdx));
   else
     CS.initAccessResistance =  {'NA'};
   end
else    
    disp('Manual entry data not found')
    CS.noManuTag = 1;
end          

anatomy = types.core.ProcessingModule(...
                     'description', 'Histological processing',...
                     'dynamictable', []  ...
                           );     
Col1 = find(strcmpi(T.Properties.VariableNames,'SomaLayerLoc'));
Col2 = find(strcmpi(T.Properties.VariableNames,'DendriticType'));
Col3 = find(strcmpi(T.Properties.VariableNames,'PyrID'));

Tab = T(CS.CompDataIdx, [Col1 Col2 Col3]);  
anatomy.dynamictable.set('histology', types.hdmf_common.DynamicTable( ...
    'description', 'Important anatomical data of cell', ...
    'colnames', {'SomaLayerLoc', 'DendriticType', 'PyrID' }, ...
    'SomaLayerLoc', types.hdmf_common.VectorData(...
        'description', 'Home layer of the cell soma', ...
         'data', char(Tab{:,1})), ...
    'DendriticType',  types.hdmf_common.VectorData(...
        'description', 'Dendritic type of the cell: either aspiny or spiny', ...
          'data', char(Tab{:,2})), ...
     'PyrID',  types.hdmf_common.VectorData(...
        'description', 'Dendritic type of the cell: either aspiny or spiny', ...
          'data', char(Tab{:,3})),...
     'id', types.hdmf_common.ElementIdentifiers('data', uint32(0))...
              ));

if isempty(Tab{:,3})
  anatomy.dynamictable.values{1}.vectordata.values{3}.data = 'NA';
end
if isempty(Tab{:,2})
  anatomy.dynamictable.values{1}.vectordata.values{2}.data = 'NA';
end
if isempty(Tab{:,1})
  anatomy.dynamictable.values{1}.vectordata.values{1}.data = 'NA';    
end

nwb.processing.set('misc', anatomy); 
end